### ISSUE TITLE
Flyer - working files

### ISSUE THREAD

**Issue by eallenOP** [bit-Pro/team-deliverables-green#5]
Could you please include the original working project (Publisher?) for the flyer so that if I need to access it for some reason I'll be able to find it straight away? All I can currently see is a pdf in your working directory.

**Comment by woodjj1** [comment]
Hi Elise,

I have passed this on this message to our team through slack as well.  Thanks for bringing this to our attention.

**Comment by LissyMcL** [comment]
I've uploaded the original publisher file into the working files folder in the master branch. My apologies for not including this earlier.

**Comment by eallenOP** [comment]
Cool, thanks for that. If the team is happy then this issue can be closed to indicate it's been dealt with.
